server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:javaserver;MODE=Oracle
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org:
      hibernate: INFO
      springframework: INFO
      springframework.mail: INFO
      springframework.security: TRACE
    com.simocaccia.auth: DEBUG
    com.zaxxer.hikari: INFO
custom:
  security:
    private-key-location: "hs256_secret"
    jwt:
      expiration-time: 86400000 #one day
test:
  security:
    secret-key: "secret_key"